# Supported Ollama Cloud Models
# Checked on: 2026-06-14
# These models are verified to succeed without requiring a paid subscription tier.

SUPPORTED_MODELS = [
    "minimax-m3:cloud",
    "nemotron-3-ultra:cloud",
    "gemma4:31b-cloud",
    "nemotron-3-super:cloud",
    "glm-4.7:cloud",
    "minimax-m2.1:cloud",
    "gpt-oss:20b-cloud",
    "gpt-oss:120b-cloud",
    "qwen3-coder:480b-cloud",
    "qwen3-vl:235b-cloud",
    "qwen3-vl:235b-instruct-cloud",
    "minimax-m2:cloud",
    "glm-4.6:cloud",
    "ministral-3:3b-cloud",
    "ministral-3:8b-cloud",
    "ministral-3:14b-cloud",
    "devstral-small-2:24b-cloud",
    "nemotron-3-nano:30b-cloud",
    "qwen3-next:80b-cloud",
    "rnj-1:8b-cloud",
    "devstral-2:123b-cloud",
    "qwen3-coder-next:cloud",
    "minimax-m2.5:cloud",
]

# All models tested (including those that failed/require subscription upgrade)
ALL_TESTED_MODELS = {
    "minimax-m3:cloud": {"supported": True, "requires_subscription": False},
    "nemotron-3-ultra:cloud": {"supported": True, "requires_subscription": False},
    "gemma4:31b-cloud": {"supported": True, "requires_subscription": False},
    "qwen3.5:cloud": {"supported": False, "requires_subscription": True},
    "qwen3.5:397b-cloud": {"supported": False, "requires_subscription": True},
    "glm-5.1:cloud": {"supported": False, "requires_subscription": True},
    "minimax-m2.7:cloud": {"supported": False, "requires_subscription": True},
    "nemotron-3-super:cloud": {"supported": True, "requires_subscription": False},
    "glm-5:cloud": {"supported": False, "requires_subscription": True},
    "kimi-k2.7-code:cloud": {"supported": False, "requires_subscription": True},
    "glm-4.7:cloud": {"supported": True, "requires_subscription": False},
    "gemini-3-flash-preview:cloud": {"supported": False, "requires_subscription": True},
    "minimax-m2.1:cloud": {"supported": True, "requires_subscription": False},
    "kimi-k2.6:cloud": {"supported": False, "requires_subscription": True},
    "deepseek-v4-pro:cloud": {"supported": False, "requires_subscription": True},
    "deepseek-v4-flash:cloud": {"supported": False, "requires_subscription": True},
    "kimi-k2.5:cloud": {"supported": False, "requires_subscription": True},
    "gpt-oss:20b-cloud": {"supported": True, "requires_subscription": False},
    "gpt-oss:120b-cloud": {"supported": True, "requires_subscription": False},
    "qwen3-coder:480b-cloud": {"supported": True, "requires_subscription": False},
    "qwen3-vl:235b-cloud": {"supported": True, "requires_subscription": False},
    "qwen3-vl:235b-instruct-cloud": {"supported": True, "requires_subscription": False},
    "deepseek-v3.2:cloud": {"supported": False, "requires_subscription": True},
    "kimi-k2-thinking:cloud": {"supported": False, "requires_subscription": True},
    "minimax-m2:cloud": {"supported": True, "requires_subscription": False},
    "glm-4.6:cloud": {"supported": True, "requires_subscription": False},
    "ministral-3:3b-cloud": {"supported": True, "requires_subscription": False},
    "ministral-3:8b-cloud": {"supported": True, "requires_subscription": False},
    "ministral-3:14b-cloud": {"supported": True, "requires_subscription": False},
    "devstral-small-2:24b-cloud": {"supported": True, "requires_subscription": False},
    "nemotron-3-nano:30b-cloud": {"supported": True, "requires_subscription": False},
    "qwen3-next:80b-cloud": {"supported": True, "requires_subscription": False},
    "rnj-1:8b-cloud": {"supported": True, "requires_subscription": False},
    "deepseek-v3.1:671b-cloud": {"supported": False, "requires_subscription": True},
    "devstral-2:123b-cloud": {"supported": True, "requires_subscription": False},
    "mistral-large-3:675b-cloud": {"supported": False, "requires_subscription": True},
    "kimi-k2:1t-cloud": {"supported": False, "requires_subscription": True},
    "qwen3-coder-next:cloud": {"supported": True, "requires_subscription": False},
    "minimax-m2.5:cloud": {"supported": True, "requires_subscription": False},
}
